Repository purposeindustries/intellyo-application-design-system, pull requests merged in 2018-05, with the labels that each got.

#378 Fix/failing nightly
  e2e/test/index-tests/index-test.js
  e2e/test/tags-input-tests/tags-input-test.js
Labels: lgtm

#379 feat: add nightly notification webhook
  .circleci/config.yml
Labels: lgtm

#380 ci: update notification url
  .circleci/config.yml
Labels: Review Needed, lgtm

#381 feat(loading button): add disabled prop
  src/components/loading-button/README.md
  src/components/loading-button/index.js
Labels: lgtm

#382 feat(tile): add normal size
  src/components/tile/README.md
  src/components/tile/index.js
  src/postcss/avatar.css
  src/postcss/tile.css
  src/postcss/variables.css
Labels: lgtm

#383 chore: rename nihglty build e2e tests
  .circleci/config.yml
Labels: lgtm

#385 ci: always create latest tag and run e2e test
  .circleci/config.yml
Labels: lgtm

#386 ci: turn off nightly build for latest tag
  .circleci/config.yml
Labels: Review Needed

#388 fix(avatar): fallback to silhouette on load error.
  src/components/avatar/index.js
  src/pages/avatars.js
  src/postcss/avatar.css
Labels: lgtm
