Repository purposeindustries/intellyo-application-design-system, pull requests merged in 2018-03, with the labels that each got.

#326 Feat/add custom texts to loading button
  e2e/test/buttons-tests/buttons-test.js
  src/components/loading-button/README.md
  src/components/loading-button/index.js
  src/pages/buttons.js
  src/postcss/pages/buttons.css
Labels: lgtm

#325 Feat(modal): scroll
  src/components/modals/index.js
  src/pages/modals.js
  src/postcss/modal.css
  src/postcss/variables.css
Labels: lgtm

#328 Fix/(confirmation + modal): fix missing export, autoheight
  src/components/index.js
  src/components/modals/index.js
Labels: lgtm

#323 fix (overlay trigger): implement click outside
  package.json
  src/components/overlay-trigger/index.js
Labels: Breaking change, lgtm

#334 Fix/modal improvement
  src/components/modals/README.md
  src/components/modals/index.js
Labels: lgtm

#335 Feat/update modal styles
  e2e/test/modal-tests/pics/reference/fef-modal-tests/should-check-modal-with-animation/modal-with-animation_reference_pic.png
  e2e/test/modal-tests/pics/reference/fef-modal-tests/should-check-modal/modal_reference_pic.png
  src/pages/modals.js
  src/postcss/modal.css
Labels: Review Needed, sync

#314 Feat/update textarea styles
  src/postcss/colors.css
  src/postcss/textarea.css
  src/postcss/variables.css
Labels: Review Needed, sync

#307 Feat/update dropdown styles
  e2e/test/buttons-tests/pics/reference/fef-buttons-tests/should-check-the-button-with-mouseover:-yeah-button-mouseover/yeah-button-mouseover_reference_pic.png
  e2e/test/buttons-tests/pics/reference/fef-buttons-tests/should-check-the-button:-yeah-button/yeah-button_reference_pic.png
  e2e/test/select-tests/pics/reference/fef-select-tests/should-check-the-input-select-hello-closed/select-hello-closed_reference_pic.png
  e2e/test/select-tests/pics/reference/fef-select-tests/should-check-the-input-select-hello-opened/select-hello-opened_reference_pic.png
  e2e/test/select-tests/pics/reference/fef-select-tests/should-check-the-input-select-hello/select-hello_reference_pic.png
  src/postcss/dropdown.css
  src/postcss/multiselect.css
  src/postcss/select.css
  src/postcss/variables.css
Labels: Review Needed, sync

#320 feat(select): add classname to select + gray out unselected dropdown text
  src/components/dropdown/index.js
  src/components/select/index.js
  src/postcss/select.css
Labels: lgtm

#303 Feat/update button styles
  e2e/test/buttons-tests/pics/reference/fef-buttons-tests/should-check-the-button:-save-button-loading/save-button-loading_reference_pic.png
  e2e/test/buttons-tests/pics/reference/fef-buttons-tests/should-check-the-button:-save-button/save-button_reference_pic.png
  e2e/test/section-tests/pics/reference/fef-sections-tests/should-check-the-section-danger-zone-button-mouseover/danger-zone-button-mouseover_reference_pic.png
  e2e/test/section-tests/pics/reference/fef-sections-tests/should-check-the-section-danger-zone/danger-zone_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-hamburger-click-tag/hamburger-click-tag_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-hamburger-mouseover-tag/hamburger-mouseover-tag_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-hamburger-tag/hamburger-tag_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-tags-input-add-input-click/tags-input-add-input-click_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-tags-input-add-input/tags-input-add-input_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-tags-input-click/tags-input-click_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-tags-input-mouse-over/tags-input-mouse-over_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-tags-input/tags-input_reference_pic.png
  src/postcss/button.css
  src/postcss/pages/typography.css
  src/postcss/tagsinput.css
  src/postcss/variables.css
Labels: lgtm, sync

#327 refactor(Avatar)
  README.md
  e2e/test/tooltip-tests/pics/reference/fef-tooltip-tests/checks-the-the-fef-tooltips-page-title-and-browser-compare-visual-regression/whole_page_reference.png
  e2e/test/tooltip-tests/pics/reference/fef-tooltip-tests/should-check-tooltip-right/tooltip-right_reference_pic.png
  e2e/test/tooltip-tests/tooltip-test.js
  package-lock.json
  package.json
  src/components/avatar-card/README.md
  src/components/avatar-card/index.js
  src/components/avatar/README.md
  src/components/avatar/index.js
  src/components/index.js
  src/pages/avatars.js
  src/postcss/avatar-card.css
  src/postcss/avatar.css
  src/postcss/main.css
  src/postcss/stacked-avatar.css
  src/postcss/variables.css
Labels: Breaking change, do not merge, lgtm

#338 feat(multiselect): add selected label prop for i18n
  src/components/multiselect/README.md
  src/components/multiselect/index.js
  src/pages/select.js
  src/postcss/multiselect.css
Labels: lgtm

#339 fix(options): change prop types to node
  src/components/option-separator/README.md
  src/components/option-separator/index.js
  src/components/option/README.md
  src/components/option/index.js
Labels: lgtm

#306 feat/sync styles between FEF and Sketch
  e2e/test/accordion-tests/pics/reference/fef-accordions-tests/should-check-basic-info-accordion-open/basic-info-accordion-open_reference_pic.png
  e2e/test/accordion-tests/pics/reference/fef-accordions-tests/should-check-basic-info-accordion/basic-info-accordion_reference_pic.png
  e2e/test/avatar-tests/pics/reference/fef-avatars-tests/should-check-avatar-upload-file/upload-file_reference_pic.png
  e2e/test/buttons-tests/buttons-test.js
  e2e/test/buttons-tests/pics/reference/fef-buttons-tests/should-check-the-button-with-mouseover:-yeah-button-mouseover/yeah-button-mouseover_reference_pic.png
  e2e/test/buttons-tests/pics/reference/fef-buttons-tests/should-check-the-button:-save-button-loading/save-button-loading_reference_pic.png
  e2e/test/buttons-tests/pics/reference/fef-buttons-tests/should-check-the-button:-save-button/save-button_reference_pic.png
  e2e/test/buttons-tests/pics/reference/fef-buttons-tests/should-check-the-button:-yeah-button/yeah-button_reference_pic.png
  e2e/test/card-tests/pics/reference/fef-card-tests/should-check-card-with-caption-and-i/card-with-caption-and-i_reference_pic.png
  e2e/test/card-tests/pics/reference/fef-card-tests/should-check-card-with-caption/card-with-caption_reference_pic.png
  e2e/test/card-tests/pics/reference/fef-card-tests/should-check-card/card_reference_pic.png
  e2e/test/input-tests/pics/reference/fef-input-tests/should-check-basic-input-added-text/basic-input-added-text_reference_pic.png
  e2e/test/input-tests/pics/reference/fef-input-tests/should-check-basic-input-clicked/basic-input-clicked_reference_pic.png
  e2e/test/input-tests/pics/reference/fef-input-tests/should-check-basic-input/basic-input_reference_pic.png
  e2e/test/modal-tests/pics/reference/fef-modal-tests/should-check-modal-with-animation/modal-with-animation_reference_pic.png
  e2e/test/modal-tests/pics/reference/fef-modal-tests/should-check-modal/modal_reference_pic.png
  e2e/test/popver-tests/pics/reference/fef-popover-tests/should-check-click-popover/click-popover_reference_pic.png
  e2e/test/popver-tests/pics/reference/fef-popover-tests/should-check-hover-popover/hover-popover_reference_pic.png
  e2e/test/popver-tests/pics/reference/fef-popover-tests/should-check-overlay-popover/overlay-popover_reference_pic.png
  e2e/test/section-tests/pics/reference/fef-sections-tests/should-check-the-section-danger-zone-button-mouseover/danger-zone-button-mouseover_reference_pic.png
  e2e/test/section-tests/pics/reference/fef-sections-tests/should-check-the-section-danger-zone/danger-zone_reference_pic.png
  e2e/test/section-tests/section-test.js
  e2e/test/select-tests/pics/reference/fef-select-tests/should-check-the-input-select-hello-closed/select-hello-closed_reference_pic.png
  e2e/test/select-tests/pics/reference/fef-select-tests/should-check-the-input-select-hello-opened/select-hello-opened_reference_pic.png
  e2e/test/select-tests/pics/reference/fef-select-tests/should-check-the-input-select-hello/select-hello_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-hamburger-click-tag/hamburger-click-tag_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-hamburger-mouseover-tag/hamburger-mouseover-tag_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-hamburger-tag/hamburger-tag_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-tags-input-add-input-click/tags-input-add-input-click_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-tags-input-add-input/tags-input-add-input_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-tags-input-click/tags-input-click_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-tags-input-mouse-over/tags-input-mouse-over_reference_pic.png
  e2e/test/tags-input-tests/pics/reference/fef-tags-input-tests/should-check-the-input:-tags-input/tags-input_reference_pic.png
  e2e/test/tooltip-tests/pics/reference/fef-tooltip-tests/checks-the-the-fef-tooltips-page-title-and-browser-compare-visual-regression/whole_page_reference.png
  e2e/test/tooltip-tests/pics/reference/fef-tooltip-tests/should-check-tooltip-right/tooltip-right_reference_pic.png
  package-lock.json
  package.json
  src/components/dropdown/index.js
  src/components/select/index.js
  src/pages/modals.js
  src/postcss/button.css
  src/postcss/colors.css
  src/postcss/dropdown.css
  src/postcss/input.css
  src/postcss/modal.css
  src/postcss/multiselect.css
  src/postcss/pages/typography.css
  src/postcss/select.css
  src/postcss/tagsinput.css
  src/postcss/textarea.css
  src/postcss/variables.css
Labels: Breaking change, sync

#299 Add links to UX index page
  src/components/sidebar/index.js
  src/pages/index.js
  src/postcss/main.css
  src/postcss/pages/index-page.css
Labels: lgtm

#343 ignore e2e in force builds
  circle.yml
Labels: Review Needed

#341 chor(modal): complete readme with autoscroll
  src/components/modals/README.md
Labels: lgtm

#345 Chore/force build option
  .circleci/config.yml
Labels: Review Needed

#348 Chore/workflow schedule
  .circleci/config.yml
Labels: Review Needed

#337 feat(checkbox): add new component
  README.md
  src/components/checkbox/README.md
  src/components/checkbox/index.js
  src/components/index.js
  src/pages/select.js
  src/postcss/checkbox.css
  src/postcss/main.css
  src/postcss/pages/select.css
Labels: lgtm

#350 fix(TabPanel): add toArray to be able to filter out null children
  src/components/tab-panel/index.js
Labels: lgtm

#353 match tag and branch in deploy
  .circleci/config.yml
Labels: Review Needed

#351 fix(dropdown): change string prop types to node
  src/components/dropdown-item/README.md
  src/components/dropdown-item/index.js
  src/components/dropdown/README.md
  src/components/dropdown/index.js
Labels: lgtm

#354 matching tag on circleci
  .circleci/config.yml
Labels: Review Needed

#355 separate pre version deploy
  .circleci/config.yml
Labels: Review Needed

#342 fix(list): enable user select
  src/components/list/dragSort.js
  src/postcss/list.css
Labels: lgtm

#356 Fix(select, input): change proptypes
  src/components/input/README.md
  src/components/input/index.js
  src/components/select/README.md
  src/components/select/index.js
Labels: lgtm

#358 Test/fix master tests
  .circleci/config.yml
  e2e/test/avatar-tests/pics/reference/fef-avatars-tests/should-check-avatar-upload-file/upload-file_reference_pic.png
  e2e/test/buttons-tests/buttons-test.js
  e2e/test/buttons-tests/pics/reference/fef-buttons-tests/should-check-the-button:-save-button-loading/save-button-loading_reference_pic.png
  e2e/test/buttons-tests/pics/reference/fef-buttons-tests/should-check-the-button:-save-button/save-button_reference_pic.png
  e2e/test/buttons-tests/pics/reference/fef-buttons-tests/should-check-the-button:-yeah-button/yeah-button_reference_pic.png
  e2e/test/index-tests/index-test.js
  e2e/test/input-tests/input-test.js
  e2e/test/popver-tests/pics/reference/fef-popover-tests/should-check-click-popover/click-popover_reference_pic.png
  e2e/test/popver-tests/popover-test.js
  e2e/test/section-tests/pics/reference/fef-sections-tests/should-check-the-section-danger-zone/danger-zone_reference_pic.png
  e2e/test/section-tests/section-test.js
  e2e/test/select-tests/pics/reference/fef-select-tests/should-check-the-input-select-hello-closed/select-hello-closed_reference_pic.png
  e2e/test/select-tests/select-test.js
  e2e/test/tags-input-tests/tags-input-test.js
  e2e/utils/visual-regression.js
Labels: lgtm

#359 docs: release and deploy docs
  README.md
Labels: lgtm

#362 Chore/nightly build set up
  .circleci/config.yml
Labels: lgtm

#364 generate changelog
  CHANGELOG.md
  package.json
Labels: lgtm

#365 create and upload release.tar.gz for preversions
  .circleci/config.yml
Labels: lgtm
